version: 0.2

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - echo "Build completed"

  post_build:
    commands:
      - echo "Deploying to EC2"

      - printf "%s" "$EC2_KEY" > key.pem
      - chmod 400 key.pem

      - |
        ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@<EC2-IP> "
        cd poc-22 &&
        git pull &&
        npm install &&
        pkill -f app.js || true &&
        nohup node app.js > app.log 2>&1 &
        "
