version: 0.2
 
phases:
  install:
    commands:
      - npm install
 
  build:
    commands:
      - echo "Build complete"
 
 
post_build:
  commands:
    - echo "$EC2_KEY" | base64 -d > key.pem
    - chmod 400 key.pem
    - ssh -i key.pem -o StrictHostKeyChecking=no ec2-user@54.252.206.73 "cd poc22 && git pull && npm install && pkill node || true && nohup node app.js > app.log 2>&1 &"
